
package com.sks;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://sks.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "addStudentReturn", targetNamespace = "http://sks.com")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://sks.com", className = "com.sks.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://sks.com", className = "com.sks.AddStudentResponse")
    public boolean addStudent();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "deleteStudentReturn", targetNamespace = "http://sks.com")
    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://sks.com", className = "com.sks.DeleteStudent")
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://sks.com", className = "com.sks.DeleteStudentResponse")
    public boolean deleteStudent();

    /**
     * 
     * @return
     *     returns java.util.List<com.sks.Student>
     */
    @WebMethod
    @WebResult(name = "getAllStudentReturn", targetNamespace = "http://sks.com")
    @RequestWrapper(localName = "getAllStudent", targetNamespace = "http://sks.com", className = "com.sks.GetAllStudent")
    @ResponseWrapper(localName = "getAllStudentResponse", targetNamespace = "http://sks.com", className = "com.sks.GetAllStudentResponse")
    public List<Student> getAllStudent();

}
